name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency: new-build

jobs:
  build:
    name: msbuild
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build app for release
      run: msbuild .\src\NaviDoctor\NaviDoctor.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
