name: Build

on:
  push:
    branches: [ "main", "dillonzer_develop" ]
  pull_request:
    branches: [ "main" ]

concurrency: new-build

jobs:
  build:
    name: msbuild
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory . 
    - name: Build app for release
      run: msbuild .\src\NaviDoctor\NaviDoctor.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: Run UnitTests
      run: .\NUnit.ConsoleRunner.3.13.0\tools\nunit3-console.exe  .\src\NaviDoctor.Tests\bin\Debug\net6.0\NaviDoctor.Tests.dll
